### ISSUE TITLE
Missing inception_v3.h5 files

### ISSUE THREAD

**Issue by chaudatascience** [pangzss/pytorch-CTVSUM#2]
Hi,

It seems like we need `inception_v3.h5` files for tvsum and summe datasets when running`./run_y8.sh`.

```           
for name in ['tvsum', 'summe']:
       dataset = h5py.File(self.data_cfg.paths.interim+'/{}_inception_v3.h5'.format(name), 'r') 

```

Can you please let me know where to find them?

Thank you,
Bests
Chau

**Comment by pangzss** [comment]
Hi,

Sorry for the late reply.
I added the related .h5 files in the Google Drive folder in the instruction.

Best,
Zongshang.

**Comment by chaudatascience** [comment]
Thank you!
