### ISSUE TITLE
How to apply to a new dataset

### ISSUE THREAD

**Issue by hayleeXinyi** [pangzss/pytorch-CTVSUM#3]
Thanks for your great effort. I noticed you used pre-trained features, how can I get the feature if I want to use a new dataset?

**Comment by pangzss** [comment]
Hi, thank you for your interest in our work.

You can use this [repo](https://github.com/antoine77340/video_feature_extractor) to extract features for your own video dataset. For the feature extractor, you can choose the one you like.
